In [59]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.sparse.linalg import eigs


1. Markov Chain

In [60]:

# Load team names
teamNames = np.loadtxt("TeamNames.txt" , dtype='str')
print(teamNames[0])

AbileneChristian


In [61]:
# Initialize M matrix with zeros
M = np.zeros((763,763))
print(M)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [62]:
# Initialize random Walk matrix 

gameData = np.genfromtxt('CFB2017_scores.csv', delimiter=",")

In [63]:
# Update M based on the data from file

for row in gameData:
    teamAin = int(row[0])
    aPts = int(row[1])
    teamBin = int(row[2])
    bPts = int(row[3])
    
    i = teamAin - 1
    j = teamBin - 1
    
    weight = aPts/(aPts + bPts)
    win = int(aPts > bPts)
    
    M[i,i] += win + weight
    M[j,j] += (1 - win) + (1 - weight)
    M[j,i] += win + weight
    M[i,j] +=  (1 - win) + (1 - weight)
    

    
M =  M / (np.sum(M, axis = 1).reshape(-1,1))

In [64]:
print(np.sum(M[2]))

0.9999999999999999


In [65]:
# eigenval calcs

w_inf= eigs(M.T,1)[1].flatten()
w_inf = w_inf/(np.sum(w_inf))


In [68]:
# update w vector
w = np.repeat(1/763, 763)
tRank = set([10, 100, 1000, 10000])
tCol = []
w_inf_t = np.zeros(10000)

results = pd.DataFrame(index=range(25), columns=[10,100,1000,10000])

for t in range(1,10001):
    w = np.dot(w,M)
    w_inf_t[t-1] = np.sum(abs(w - w_inf)) 
    if(t in tRank):
        
        if(t in tRank):
            word_idx = np.argsort(w)[::-1][:25]
            results[t] = list(zip(teamNames[word_idx], [format(x, '.4f') for x in w[word_idx]])) 
            teamNames[np.argsort(w)[::-1][:25]]
print(results)
results.to_html('res.html')

                          10                            100    \
0          (MountUnion, 0.0184)          (MountUnion, 0.0657)   
1   (MaryHardin-Baylor, 0.0130)             (Alabama, 0.0230)   
2         (StFrancisIN, 0.0110)             (Georgia, 0.0192)   
3          (UW-Oshkosh, 0.0100)          (UW-Oshkosh, 0.0179)   
4       (TAMU-Commerce, 0.0093)           (OhioState, 0.0149)   
5         (BrockportSt, 0.0092)             (Clemson, 0.0147)   
6       (NorthDakotaSt, 0.0090)            (Oklahoma, 0.0142)   
7             (Alabama, 0.0090)           (Wisconsin, 0.0138)   
8         (Morningside, 0.0088)      (CentralFlorida, 0.0131)   
9             (Georgia, 0.0084)   (MaryHardin-Baylor, 0.0126)   
10       (JamesMadison, 0.0081)       (TAMU-Commerce, 0.0125)   
11     (DelawareValley, 0.0079)              (Auburn, 0.0120)   
12           (Wartburg, 0.0076)         (StFrancisIN, 0.0111)   
13          (IndianaPA, 0.0072)           (PennState, 0.0107)   
14            (Clemson, 0

In [36]:
print(w_inf_t)

[1.60172052 1.57250142 1.55195865 ... 1.35314014 1.35314014 1.35314014]


In [37]:
# Create ranking data frame 
tArray = tCol[0]
print(tCol[1])

for t in range(1, len(tCol)):
    #tArray = np.vstack((tArray, tCol[t]))
    if (t+1) in t_ranks:
            word_idx = np.argsort(w)[::-1][:25]
                self.results["t_%d"%(t+1)] = list(zip(
                        self.team_names[word_idx],
                        [format(x, '.3f') for x in w[word_idx]]))
tArray = tArray.T



['MountUnion' 'Alabama' 'Georgia' 'UW-Oshkosh' 'OhioState' 'Clemson'
 'Oklahoma' 'Wisconsin' 'CentralFlorida' 'MaryHardin-Baylor'
 'TAMU-Commerce' 'Auburn' 'StFrancisIN' 'PennState' 'BrockportSt'
 'NotreDame' 'DelawareValley' 'NorthDakotaSt' 'FrostburgSt' 'TCU'
 'MinnSt-Mankato' 'CaseWesternReserve' 'JohnCarroll' 'MiamiFL' 'Harding']


In [38]:
# print rankings data frame
rankingsDf = pd.DataFrame(tArray, columns=["t = 10", "t = 100", " t = 1000", "t = 10000"])
rankingsDf.index = np.arange(1, 26)
rankingsDf.to_html('rankingsTable.html')
print(rankingsDf)

               t = 10             t = 100        t = 1000        t = 10000
1          MountUnion          MountUnion         Alabama          Alabama
2   MaryHardin-Baylor             Alabama         Georgia          Georgia
3         StFrancisIN             Georgia      MountUnion        OhioState
4          UW-Oshkosh          UW-Oshkosh       OhioState          Clemson
5       TAMU-Commerce           OhioState         Clemson         Oklahoma
6         BrockportSt             Clemson        Oklahoma        Wisconsin
7       NorthDakotaSt            Oklahoma       Wisconsin   CentralFlorida
8             Alabama           Wisconsin  CentralFlorida           Auburn
9         Morningside      CentralFlorida          Auburn        PennState
10            Georgia   MaryHardin-Baylor       PennState        NotreDame
11       JamesMadison       TAMU-Commerce       NotreDame              TCU
12     DelawareValley              Auburn             TCU          MiamiFL
13           Wartburg    

In [ ]:
import matplotlib as mpl
mpl.style.use('seaborn')
plt.figure()
plt.plot(range(1,10001), w_inf_t)
plt.xlabel("Iterations t")
plt.ylabel("|w_t - w_inf|")
plt.title("|w_t - w_inf| vs t")
plt.savefig('differential.png')


Problem 2 NMF

In [ ]:
#Initialize X

X = np.zeros((3012, 8447))


In [ ]:

raw_nyt_data = np.loadtxt('nyt_data.txt', dtype='str', delimiter="\n")



In [ ]:
for i in range(0, len(raw_nyt_data)):
    temp = raw_nyt_data[i].split(',')
    for w in temp:
        temp2  = w.split(':')
        index = int(temp2[0])
        count = int(temp2[1])
        X[index-1, i] = count


In [ ]:
print(X)

In [ ]:
#Loading words 
vocab = np.loadtxt("nyt_vocab.dat" , dtype='str')



In [ ]:
print(vocab)

In [ ]:
# Initializing W and H
W = np.random.uniform(1,2,(3012,25))
H = np.random.uniform(1,2,(25,8447))



In [ ]:
# training model

objective = np.zeros(100)
matWH = np.dot(W, H)
A = np.divide(X, (matWH) + 1e-16)

In [ ]:
for i in range(0,100):
    H = np.multiply(H, np.dot(W.T, A))/(np.sum(W, axis = 0)).reshape(25,1)
    matWH = np.dot(W, H)
    A = np.divide(X, (matWH) + 1e-16)
    W = (W * np.dot(A, H.T))/(np.sum(H, axis = 1)).reshape(1,25)
    matWH = np.dot(W, H)
    A = np.divide(X, (matWH) + 1e-16)
    objVal = np.sum((np.log(1/(matWH + 1e-16)) * X ) + matWH)
    objective[i] = objVal

In [ ]:
# Print plot of objective function
mpl.style.use('seaborn')
plt.plot(range(1,101), objective)
plt.xlabel("Iterations t")
plt.ylabel("Objective Value")
plt.title("Objective Value Over Iterations t")
plt.savefig("figure2a.png")

In [ ]:
print(W)

In [ ]:
# normalize and get words
Wnorm = W /(np.sum(W, axis=0).reshape(1,-1))
print(np.sum(Wnorm[:,0]))

In [ ]:
windex = np.zeros((10,25),dtype=int)
for i in range(0,25):
    windex[:,i] = np.argsort(Wnorm[:,i][-10:][::-1])

data = pd.DataFrame(index=range(1,11), columns=['Topic %d'%i for i in range(1,26)])
for i in range(25):
    for x in range(0,10):
        data.iloc[:,i][x] = {vocab[windex[:,i]][x]: format(Wnorm[windex[:,i],i][x], '.4f')}
            
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
display(results)


results.to_html('figure2b.html',index=False)
