In [2]:
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
plt.rcParams["figure.figsize"] = (10,8)

In [3]:
class LeastSquaresRegression(object):
    def __init__(self):
        self.weights = []
    
    def calcLeastSquares(self, X, y):
        xtranspose = np.transpose(X)
        xtransx = np.dot(xtranspose, X)
        if xtransx.shape[0] != xtransx.shape[1]:
            raise ValueError('Needs to be a square matrix for inverse')
        matinv = np.linalg.inv(xtransx)
        xtransy = np.dot(xtranspose, y)
        self.weights = np.dot(matinv, xtransy)

    def makePredictions(self, X):
        class_output = np.dot(X, self.weights)
        return np.sign(class_output)

In [39]:
class Boosting(object):

    def __init__(self, X_train, y_train):
        self.X_train = X_train
        self.N = self.X_train.shape[0]
        self.y_train = y_train
        self.weights = np.ones(self.N)/self.N
        self.epsilont = []
        self.alphas = []
        self.classifiers = []
        self.histogram = {}
        #self.num_estimators = T
        
    def doBoosting(self):
#         for t in range(self.num_estimators):
        for t in range(4):
            #print(self.weights)
            output = np.random.choice(self.N, self.N, p=self.weights)
            
            for t in output:
                self.histogram[t] = self.histogram.get(t, 0) + 1
            
#             print output
            B_Xtrain = self.X_train[output]
            B_ytrain = self.y_train[output]
        
            ls = LeastSquaresRegression()
            ls.calcLeastSquares(B_Xtrain, B_ytrain)
            

#             print ls.weights
            Y_pred = ls.makePredictions(self.X_train)
            
#             print Y_pred
            
            e_t = np.sum((Y_pred != self.y_train) * self.weights)
#             print e_t
            if e_t > 0.5:
                ls.weights = -ls.weights
                Y_pred = ls.makePredictions(self.X_train)
                e_t = np.sum((Y_pred != self.y_train) * self.weights)
            
            print(e_t)
            print(ls.weights)
            print(Y_pred)
            
#             print e_t
            self.epsilont.append(e_t)

            alpha_t = 0.5 * np.log((1 - e_t)/e_t)
            self.alphas.append(alpha_t)
            self.classifiers.append(ls)
            
#             print alpha_t   
            self.weights = self.weights * np.exp(-alpha_t* Y_pred * self.y_train)
            self.weights = self.weights / np.sum(self.weights)

In [40]:
X_train = np.genfromtxt('hw3-data/boosting/X_train.csv', delimiter=',')
y_train = np.genfromtxt('hw3-data/boosting/y_train.csv')
X_test = np.genfromtxt('hw3-data/boosting/X_test.csv', delimiter=',')
y_test = np.genfromtxt('hw3-data/boosting/y_test.csv')


def append_column_one(data):    
    append_ones = np.ones((data.shape[0],1))
    data = np.hstack((append_ones, data))
    return data

X_train = append_column_one(X_train)
X_test = append_column_one(X_test)


In [45]:
boost = Boosting(X_train, y_train)
boost.doBoosting()

0.013513513513513514
[-0.56572543 -0.43459339 -1.2314249   0.73468147  0.08984443  1.26668068]
[1. 1. 1. ... 1. 1. 1.]
0.09001956947162429
[-0.71810392  0.738775    3.50346273 -0.06514661  0.8688013  -3.73933257]
[-1. -1. -1. ... -1. -1. -1.]
0.2809490416082282
[-0.55257974  1.1791866   4.7922803   0.26736572  0.76423766 -5.14137023]
[-1. -1. -1. ... -1. -1. -1.]
0.34502009653565346
[-0.4632904   0.93435956  4.10652626  0.21594947  0.45598774 -4.22035481]
[-1. -1. -1. ... -1. -1. -1.]


In [25]:
print(boost.N)

1036


In [8]:
print(boost.epsilont)
print(boost.alphas)

[0.012548262548262547, 0.0855327468230694, 0.2749795901586388, 0.39453664664556587, 0.38016996270405684, 0.4589055660810455, 0.494300308454581, 0.4863521126374691, 0.4683799676099575, 0.4733787112151282, 0.4364590909357463, 0.439728958493079, 0.4933973611712409, 0.4956417582206707, 0.46172863386133567, 0.49906097007488437, 0.4515921109245207, 0.4981041752526476, 0.43096964326731474, 0.4415659342789765, 0.4617238312499633, 0.46573221043247215, 0.4793226044909006, 0.4627949583427971, 0.4793104614646709, 0.46826131423266854, 0.4874378242338937, 0.3846972328272523, 0.4747479463289561, 0.4911824870588819, 0.4550429055910822, 0.49943271034740166, 0.4781051125452955, 0.49061096960819606, 0.4560826807572696, 0.48726614607660157, 0.4051581978464449, 0.37624263707326394, 0.40958909139637534, 0.449309358059709, 0.49379588338697256, 0.4614472010231968, 0.39911633495580495, 0.4681805202947437, 0.4961575636204274, 0.4353207111242119, 0.47250169834570543, 0.4755698797064244, 0.45604640433178667, 0.40